project:
  type: manuscript
  output-dir: docs

website:
  site-url: https://tscnlab.github.io/ZaunerDeVriesEtAl_JExpoSciEnvironEpidemiol_2026/

execute:
  freeze: auto

format:
  html:
    toc: true
    comments:
      hypothesis: true
    canonical-url: true
  # docx: default
  # jats: default
  # agu-pdf: default



